version: 2
jobs:
  build:
    docker:
      - image: circleci/node:carbon

    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Test and Collect Coverage Reports"
          command: npm run coverage

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
